[package]
name = "raillier"
version = "0.1.0"
authors = ["William <w.wischlinsky@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2.3"
rand = "0.7.0"
num-integer = "0.1.41"